# Generated by Django 4.2.2 on 2023-06-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0002_alter_review_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='library_id',
            new_name='libraryId',
        ),
        migrations.AddField(
            model_name='library',
            name='game',
            field=models.ManyToManyField(to='steam_app.game'),
        ),
        migrations.AddField(
            model_name='review',
            name='gameID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='steam_app.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='wishListId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='steam_app.wishlist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievedby',
            name='achievementID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.achievement'),
        ),
        migrations.AlterField(
            model_name='achievedby',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.user'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='gameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.game'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='gameID',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='gameID',
            field=models.ManyToManyField(to='steam_app.game'),
        ),
    ]
