# Generated by Django 4.2.2 on 2023-06-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0003_rename_library_id_user_libraryid_library_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='libraryId',
        ),
    ]
