# Generated by Django 4.2.2 on 2023-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0006_alter_game_release_date_alter_library_timeplayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(),
        ),
    ]
