# Generated by Django 4.2.2 on 2023-06-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0009_rename_achievementid_achievedby_achievement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='gameID',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='userID',
            new_name='user',
        ),
    ]
