# Generated by Django 4.2.2 on 2023-06-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0012_rename_user_steamuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='game',
            new_name='games',
        ),
    ]
