# Generated by Django 4.2.2 on 2023-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0017_rename_gameid_wishlist_wished_games'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='steamuser',
            constraint=models.UniqueConstraint(fields=('username',), name='unique_username'),
        ),
    ]
