# Generated by Django 4.2.2 on 2023-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0018_steamuser_unique_username'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_game_name'),
        ),
    ]
