# Generated by Django 4.2.2 on 2023-06-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0019_game_unique_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='cloudSaveStatus',
        ),
        migrations.RemoveField(
            model_name='library',
            name='games',
        ),
        migrations.RemoveField(
            model_name='library',
            name='lastPlayed',
        ),
        migrations.RemoveField(
            model_name='library',
            name='timePlayed',
        ),
        migrations.CreateModel(
            name='GamesInLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePlayed', models.DurationField()),
                ('lastPlayed', models.DateTimeField()),
                ('cloudSaveStatus', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.game')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.library')),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='games_in_lib',
            field=models.ManyToManyField(through='steam_app.GamesInLibrary', to='steam_app.game'),
        ),
    ]
