# Generated by Django 4.2.2 on 2023-06-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0020_remove_library_cloudsavestatus_remove_library_games_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='game',
            name='Test Int Constraint',
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 100))), name='correct_rating'),
        ),
    ]
