# Generated by Django 4.2.2 on 2023-06-27 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0021_remove_game_test_int_constraint_game_correct_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
