# Generated by Django 4.2.2 on 2023-06-27 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0023_alter_game_price_alter_game_usk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steamuser',
            name='level',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
