# Generated by Django 4.2.2 on 2023-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0024_alter_steamuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesinlibrary',
            name='lastPlayed',
            field=models.DateTimeField(),
        ),
    ]
