# Generated by Django 4.2.2 on 2023-06-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('achievementID', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('gameID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('franchise', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=2, max_digits=100)),
                ('rating', models.SmallIntegerField()),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('usk', models.SmallIntegerField()),
                ('supported_platforms', models.CharField(default='PC', max_length=200)),
                ('supported_languages', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timePlayed', models.DateTimeField()),
                ('lastPlayed', models.DateTimeField()),
                ('cloudSaveStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Undefined', max_length=200)),
                ('text', models.CharField(max_length=200, null=True)),
                ('rating', models.SmallIntegerField()),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('vac', models.BooleanField()),
                ('level', models.IntegerField()),
                ('library_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='steam_app.library')),
            ],
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (0, 100))), name='Test Int Constraint'),
        ),
    ]
