# Generated by Django 4.2.2 on 2023-06-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steam_app.user'),
        ),
    ]
