# Generated by Django 4.2.2 on 2023-06-21 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0004_remove_user_libraryid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='wishListId',
            new_name='wishList',
        ),
        migrations.AddField(
            model_name='user',
            name='library',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='steam_app.library'),
            preserve_default=False,
        ),
    ]
