# Generated by Django 4.2.2 on 2023-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0005_rename_wishlistid_user_wishlist_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='library',
            name='timePlayed',
            field=models.DurationField(),
        ),
    ]
