# Generated by Django 4.2.2 on 2023-06-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0007_alter_user_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='gameID',
            new_name='game',
        ),
    ]
