# Generated by Django 4.2.2 on 2023-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0008_rename_gameid_achievement_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievedby',
            old_name='achievementID',
            new_name='achievement',
        ),
        migrations.RenameField(
            model_name='achievedby',
            old_name='userID',
            new_name='user',
        ),
    ]
