# Generated by Django 4.2.2 on 2023-06-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0010_rename_gameid_review_game_rename_userid_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='version',
            field=models.CharField(default=1.0, max_length=20),
            preserve_default=False,
        ),
    ]
