# Generated by Django 4.2.2 on 2023-06-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0011_game_version'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='SteamUser',
        ),
    ]
