# Generated by Django 4.2.2 on 2023-06-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0013_rename_game_library_games'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='achievedby',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_achievement_unlock'),
        ),
    ]
