# Generated by Django 4.2.2 on 2023-06-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0014_achievedby_unique_achievement_unlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steamuser',
            name='library',
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='steam_app.steamuser'),
            preserve_default=False,
        ),
    ]
