# Generated by Django 4.2.2 on 2023-06-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steam_app', '0016_remove_steamuser_wishlist_wishlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='gameID',
            new_name='wished_Games',
        ),
    ]
